### ISSUE TITLE
No "configure" file

### ISSUE THREAD

**Issue by senden9** [moxie0/sslsniff#10]
In "README":
- Unpack sslsniff-0.8.tar.gz, run "./configure" and "make". (You'll have
    to make some changes to build on BSD systems, see below under "Setting up 
    pf")

There is no "configure" file.

**Comment by wsot** [comment]
To create the configure file you need to run a few commands. Go to the directory to which you extracted the files/did the repository pull then run:
aclocal
autoconf
automake --add-missing

Then you can run ./configure and make
